version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: devrick1/reverseproxy 
  backend_user:
    build:
      context: ../../app/restapi-user
    image: devrick1/restapi-user
  backend_feed:
    build:
      context: ../../app/restapi-feed  
    image: devrick1/restapi-feed
  frontend:
    build:
      context: ../../app/frontend  
    image: devrick1/frontend:local
