version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dev-rick/reverseproxy 
  backend_user:
    build:
      context: ../../restapi-user
    image: dev-rick/restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: dev-rick/restapi-feed
  frontend:
    build:
      context: ../../frontend  
    image: dev-rick/frontend:local
