version: "3"
services:
  reverseproxy:
      image: devrick1/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: devrick1/restapi-user
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DATABASE: ${POSTGRESS_DATABASE} 
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
  backend-feed:
    image: devrick1/restapi-feed
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DATABASE: ${POSTGRESS_DATABASE} 
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  frontend:
    image: devrick1/frontend:local
    ports:
      - "8100:80"
